# Generated by Django 4.2.4 on 2023-08-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230817_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='detail_adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
