# Generated by Django 3.2.20 on 2023-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_detail_adress_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='image',
            field=models.ImageField(default='merchant/jagmuldan.png', upload_to='merchant/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='restaurant_user/'),
        ),
    ]
