# Generated by Django 3.2.20 on 2023-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230818_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='image',
            field=models.ImageField(upload_to='merchant/'),
        ),
    ]
