# Generated by Django 4.2.4 on 2023-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.BooleanField(default=False)),
                ('context', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JointShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, null=True)),
                ('where', models.CharField(choices=[('서울특별시', '서울특별시'), ('경기도', '경기도'), ('인천광역시', '인천광역시'), ('강원특별자치도', '강원특별자치도'), ('대전광역시', '대전광역시'), ('세종특별자치도', '세종특별자치도'), ('충청남도', '충청남도'), ('충청북도', '충청북도'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('대구광역시', '대구광역시'), ('광주광역시', '광주광역시'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('제주특별자치도', '제주특별자치도')], default='', max_length=10)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
