# Generated by Django 3.2.20 on 2023-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_review_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointshipping',
            name='detail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
