# Generated by Django 3.2.20 on 2023-08-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_jointshipping_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='context',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
