# Generated by Django 3.2.20 on 2023-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_wirter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='wirter',
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.BooleanField(default=False),
        ),
    ]
